* dot-emacs

my emacs config!

> *DISCLAIMER* AUTHOR will be not responsible for the harm cause done
by using this config, its not likely to harm (but there are always
some assholes lying around to blame). *MAKE SURE YOU HAVE THE BACKUP*

#+ATTR_HTML: title="screenshot"
[[https://www.google.com][file:https://raw.githubusercontent.com/rhoit/dot-emacs/dump/screenshot/screenshot_01.png]]

** Getting it

#+begin_src shell
git clone --recursive https://github.com/rhoit/dot-emacs
#+end_src

*** oops!
if you accidently forgot --recursive then

#+begin_src shell
git clone https://github.com/rhoit/dot-emacs
cd dot-emacs
git submodule init
git submodule update
#+end_src

*** to build

> *NOTE* Build is kinda broken for now. Will *fix it some day*, not like
I have to install config every day! So STFU!

#+begin_src shell
  ./configure
  make
  make install
#+end_src

> *NOTE* you might need to do some el-get [[http://tapoueh.org/emacs/el-get.html][config]], yourself its too
much work to make the auto-installer (send me patch if you did).


** Structure

dot-emacs
├── el-get                 # package manager linux addicts
├── plug-ins               # packages with mods and config
│   ├── config             # custom config of packages
│   │   ├── compile.cfg.el
│   │   └── tabbar.cfg.el
│   ├── ...
:   :
│   └── tabbar-ruler.el
├── ...
:
├── repo                   # submoduled packages not yet in el-get
└── snippets               # ya-snippet stuffs
    └── python-mode
